<Menu>:
    BoxLayout:
        BoxLayout:
        BoxLayout:
            padding:"5dp"
            spacing:"30dp"
            orientation:"vertical"
            Widget:
            Botao:
                text:"Tela"
                on_release:app.root.current = "tela"
            Botao:
                text:"Sair"
                on_release:root.confirmacao()
            Widget:
        BoxLayout: 
    